修复播放视频时闪退
java.lang.RuntimeException: Class cannot be created (missing no-arg constructor): com.kuaishou.akdanmaku.ecs.component.xxx